# Generated by Django 4.2.11 on 2026-05-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_assigned_coach_customuser_last_ad_view_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('coach', 'Coach'), ('admin', 'Admin'), ('content_writer', 'Content Writer')], default='member', max_length=20),
        ),
    ]
