# Generated by Django 4.2.11 on 2026-05-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='height',
        ),
        migrations.AddField(
            model_name='customuser',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentary'), ('lightly_active', 'Lightly Active'), ('moderately_active', 'Moderately Active'), ('very_active', 'Very Active')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bmr',
            field=models.IntegerField(blank=True, help_text='Basal Metabolic Rate in calories', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='body_fat_percentage',
            field=models.FloatField(blank=True, help_text='Estimated body fat %', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dietary_preference',
            field=models.CharField(blank=True, choices=[('omnivore', 'Omnivore'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('keto', 'Keto'), ('no_preference', 'No Preference')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fitness_goal',
            field=models.CharField(blank=True, choices=[('lose_weight', 'Lose Weight'), ('gain_muscle', 'Gain Muscle'), ('maintain', 'Maintain'), ('improve_health', 'Improve Health')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='height_ft',
            field=models.IntegerField(blank=True, help_text='Height feet', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='height_in',
            field=models.IntegerField(blank=True, help_text='Height inches', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tdee',
            field=models.IntegerField(blank=True, help_text='Total Daily Energy Expenditure in calories', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in lbs', null=True),
        ),
    ]
