# Generated by Django 4.2.11 on 2026-05-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_height_customuser_activity_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bmi',
            field=models.FloatField(blank=True, help_text='Body Mass Index', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='muscle_mass_kg',
            field=models.FloatField(blank=True, help_text='Estimated muscle mass in kg', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_units',
            field=models.CharField(choices=[('metric', 'Metric'), ('imperial', 'Imperial')], default='imperial', max_length=20),
        ),
    ]
