# Generated by Django 4.2.11 on 2026-05-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_bmi_customuser_muscle_mass_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='custom_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
