# Generated by Django 4.2.11 on 2026-05-07 08:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='feature_icons/')),
                ('category', models.CharField(choices=[('workouts', 'Workouts'), ('nutrition', 'Nutrition'), ('tracking', 'Tracking'), ('community', 'Community'), ('support', 'Support'), ('other', 'Other')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('stripe_product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, null=True)),
                ('duration_days', models.IntegerField(default=30)),
                ('features', models.JSONField(default=list, help_text='List of features included in this plan')),
                ('max_workouts_per_week', models.IntegerField(default=5)),
                ('include_meal_plans', models.BooleanField(default=False)),
                ('include_personal_trainer', models.BooleanField(default=False)),
                ('include_nutrition_consultation', models.BooleanField(default=False)),
                ('include_community_access', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'price'],
            },
        ),
    ]
