# Generated by Django 4.2.11 on 2026-05-10 12:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro'), ('elite', 'Elite')], max_length=20, unique=True)),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list)),
                ('sessions_per_week', models.IntegerField(default=0, help_text='1-on-1 sessions per week')),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='features',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='include_community_access',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='include_meal_plans',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='include_nutrition_consultation',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='include_personal_trainer',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_workouts_per_week',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='stripe_product_id',
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='subscriptions.subscriptiontier'),
        ),
    ]
