# Generated by Django 4.2.11 on 2026-05-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptiontier_remove_subscriptionplan_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontier',
            name='name',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('elite', 'Elite'), ('custom', 'Custom')], max_length=20, unique=True),
        ),
    ]
