# Generated by Django 4.2.11 on 2026-05-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscriptiontier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontier',
            name='video_sessions_per_month',
            field=models.IntegerField(default=0, help_text='Video coaching sessions included per month'),
        ),
    ]
