# Generated by Django 4.2.11 on 2026-05-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_remove_old_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontier',
            name='custom_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Admin-managed hourly rate used for custom coaching packages', max_digits=10),
        ),
    ]
