# Generated by Django 4.2.11 on 2026-05-07 06:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#007BFF', help_text='Hex color code', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(help_text='Rich text content for the blog post')),
                ('excerpt', models.CharField(blank=True, help_text='Short summary shown in lists', max_length=500)),
                ('featured_image_url', models.URLField(blank=True, help_text='URL to featured image')),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('views_count', models.IntegerField(default=0)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('meta_description', models.CharField(blank=True, max_length=500)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
            ],
            options={
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('spam', 'Spam'), ('archived', 'Archived')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DynamicPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('is_visible', models.BooleanField(default=True)),
                ('show_in_footer', models.BooleanField(default=False)),
                ('show_in_menu', models.BooleanField(default=False)),
                ('meta_description', models.CharField(blank=True, max_length=500)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField()),
                ('alt_text', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(blank=True, choices=[('hero', 'Hero Images'), ('icon', 'Icons'), ('team', 'Team Photos'), ('testimonial', 'Testimonials'), ('gallery', 'Gallery'), ('logo', 'Logos'), ('banner', 'Banners'), ('other', 'Other')], max_length=50)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page', models.CharField(choices=[('home', 'Homepage'), ('about', 'About Page'), ('services', 'Services Page'), ('other', 'Other')], default='home', max_length=50)),
                ('section_type', models.CharField(choices=[('hero', 'Hero Section'), ('features', 'Features Grid'), ('pricing', 'Pricing Table'), ('testimonials', 'Testimonials'), ('cta', 'Call to Action'), ('text', 'Text Block'), ('gallery', 'Image Gallery'), ('team', 'Team Members'), ('faq', 'FAQ Section'), ('banner', 'Banner'), ('custom', 'Custom HTML')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('background_color', models.CharField(default='#FFFFFF', help_text='Hex color', max_length=7)),
                ('text_color', models.CharField(default='#000000', help_text='Hex color', max_length=7)),
                ('columns', models.IntegerField(default=3, help_text='Grid columns')),
                ('is_visible', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Lower = appears first')),
                ('cta_text', models.CharField(blank=True, help_text='Button text', max_length=100)),
                ('cta_url', models.URLField(blank=True)),
                ('cta_style', models.CharField(choices=[('primary', 'Primary Button'), ('secondary', 'Secondary Button'), ('outline', 'Outline Button')], default='primary', max_length=20)),
                ('custom_html', models.TextField(blank=True)),
                ('custom_css', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['page', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(default='FitnessPro', max_length=200)),
                ('site_tagline', models.CharField(blank=True, default='Transform Your Body, Transform Your Life', max_length=300)),
                ('site_description', models.TextField(blank=True, default='Your complete fitness subscription platform')),
                ('email', models.EmailField(default='contact@fitnessproof.com', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('logo_url', models.URLField(blank=True, help_text='URL to logo image')),
                ('favicon_url', models.URLField(blank=True, help_text='URL to favicon')),
                ('hero_image_url', models.URLField(blank=True, help_text='URL to hero/banner image')),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('meta_description', models.CharField(blank=True, max_length=500)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('language', models.CharField(default='en', max_length=10)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Settings',
                'verbose_name_plural': 'Website Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLinks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('github', 'GitHub'), ('website', 'Website')], max_length=50)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(blank=True, help_text='Font Awesome class', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('platform',)},
            },
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon code', max_length=50)),
                ('image_url', models.URLField(blank=True)),
                ('price', models.CharField(blank=True, help_text='e.g., $9.99 or Free', max_length=50)),
                ('price_period', models.CharField(blank=True, help_text='e.g., /month or /year', max_length=50)),
                ('features', models.TextField(blank=True, help_text='One feature per line')),
                ('display_order', models.IntegerField(default=0)),
                ('is_highlighted', models.BooleanField(default=False, help_text='Highlight/feature this item')),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_url', models.URLField(blank=True)),
                ('metadata', models.TextField(blank=True, help_text='Additional JSON data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.pagesection')),
            ],
            options={
                'ordering': ['section', 'display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='pagesection',
            index=models.Index(fields=['page', 'is_visible', 'display_order'], name='cms_pagesec_page_a29b1b_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['status', 'created_at'], name='cms_contact_status_e21ccd_idx'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.blogcategory'),
        ),
        migrations.AddIndex(
            model_name='sectionitem',
            index=models.Index(fields=['section', 'display_order'], name='cms_section_section_2a3651_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='cms_blogpos_slug_19f322_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', 'published_date'], name='cms_blogpos_status_5d24c3_idx'),
        ),
    ]
