# Generated by Django 4.2.11 on 2026-05-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_imageasset_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
