# Generated by Django 4.2.11 on 2026-05-12 14:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workoutprogram_workoutphase_userprogram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkoutprogress',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userworkoutprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused')], default='not_started', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('set_number', models.PositiveIntegerField()),
                ('weight', models.FloatField(blank=True, help_text='Weight used in lbs/kg', null=True)),
                ('reps', models.PositiveIntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.userworkoutprogress')),
            ],
            options={
                'ordering': ['progress', 'exercise', 'set_number'],
            },
        ),
    ]
