# Generated by Django 4.2.11 on 2026-05-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_add_phase9_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userworkoutprogress',
            name='progress_user_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='userworkoutprogress',
            name='progress_workout_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='workout',
            name='workout_creator_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='workout',
            name='workout_category_level_idx',
        ),
    ]
