# Generated by Django 4.2.11 on 2026-05-12 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_newslettersubscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
        migrations.AddField(
            model_name='coachsession',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_session_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coachsession',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('reschedule_requested', 'Reschedule Requested')], default='pending_approval', max_length=20),
        ),
    ]
