# Generated by Django 4.2.11 on 2026-05-13 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_delete_newslettersubscriber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusage',
            name='month_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiusage',
            name='monthly_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TrainerMessageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('messages_this_week', models.PositiveIntegerField(default=0)),
                ('weekly_limit', models.PositiveIntegerField(default=20)),
                ('month_start_date', models.DateField()),
                ('messages_this_month', models.PositiveIntegerField(default=0)),
                ('monthly_limit', models.PositiveIntegerField(default=80)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trainer Message Quota',
                'verbose_name_plural': 'Trainer Message Quotas',
            },
        ),
        migrations.CreateModel(
            name='TrainerMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('role', models.CharField(choices=[('coach', 'Trainer'), ('user', 'User')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_ai_generated', models.BooleanField(default=False, help_text='True if message was AI-assisted')),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'trainer'}, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_messages_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_messages_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='core_traine_user_id_0f30bf_idx'), models.Index(fields=['coach', 'timestamp'], name='core_traine_coach_i_f6b069_idx')],
            },
        ),
    ]
