# Generated by Django 4.2.11 on 2026-05-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_phase9_features_analytics'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='aichatmessage',
            name='chat_user_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='aiusage',
            name='aiusage_user_month_idx',
        ),
        migrations.RemoveIndex(
            model_name='bodymeasurement',
            name='measurement_user_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='coachsession',
            name='session_coach_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='coachsession',
            name='session_client_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='supportticket',
            name='ticket_status_priority_idx',
        ),
        migrations.RemoveIndex(
            model_name='supportticket',
            name='ticket_user_date_idx',
        ),
        migrations.RenameIndex(
            model_name='featureflag',
            new_name='core_featur_key_f90276_idx',
            old_name='feature_flag_key_active_idx',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='core_suppor_status_eeb847_idx',
            old_name='core_suppor_status_b56a31_idx',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='core_suppor_categor_8d4392_idx',
            old_name='core_suppor_category_0d3f0b_idx',
        ),
    ]
